### ISSUE TITLE
PUT method changes user password

### ISSUE THREAD

**Issue by KamilSobieraj** [jeremyben/json-server-auth#11]
What's up!

I'm using Angular 8 with json-server -auth and got a problem with PUT method. Every time I send a PUT request to users collection, it changes user password. It seems to hashing again already hashed password.

I send a request like this:
`this.httpClient
      .put<User>(this.databaseService.databaseURL + '/users/' + this.authService.getCurrentUserID(),
        JSON.stringify(updatedUserData),
        this.databaseService.httpOptions)
      .subscribe(res => console.log(res));`

It sends all data correctly but the password.
I assume I've implemented it in the wrong way. Had anyone such a problem?

I've found out that to send a PUT request, the email and password must be sent as well so I can't skip changing them. What might be the best solution for this issue?

**Comment by KamilSobieraj** [comment]
I mistaken put with patch. Please delete the issue ; )

**Comment by jeremyben** [comment]
Yep I follow json-server implementation, which *replaces* the resource with PUT. :)

**Comment by Suundumused** [comment]
> I mistaken put with patch. Please delete the issue ; )

I have the same problem, not a mistake, how did you fix this ?
