### ISSUE TITLE
How to get user profile?

### ISSUE THREAD

**Issue by Nastya-Piu** [jeremyben/json-server-auth#12]
I tried different URLs (/profile, /me) for getting user profile by assessToken but didnt find it. Please, help me to find out how to get userInfo (if it exists )??

**Comment by jeremyben** [comment]
This plugin tries to not presume too much, except for the signup and login routes, so there is no special route of that sort, you must set it up yourself.

You can access the profile in the JSON Server way with "collection/:id", by first retrieving the id from the access token.

**Comment by Nastya-Piu** [comment]
Thanks for the answer, actually I have already implemented some logic for getting a profile, will share it below:
```
const JWT_SECRET_KEY = require('./node_modules/json-server-auth/dist/constants').JWT_SECRET_KEY;
const auth = require('json-server-auth')
const server = express()
const router = jsonServer.router('db.json')

server.get('/profile', auth, (req, res, next) => {
  const token = req.header('Authorization') ? req.header('Authorization').replace('Bearer ', '') : null;
  if (token) {
    try {
      const data = jwt.verify(token, JWT_SECRET_KEY)

      const { db } = req.app;
      let user = db.get('users').find({ email: data.email }).value();
      res.json([user])
    }
    catch (error) {
      res.json({ error: error })
    }

  } else {
    res.json({ error: { name: "User not authorized" } })
  }
});

server.db = router.db
server.use(auth);
```
