### ISSUE TITLE
DOS line endings are not compatible with Unix based systems

### ISSUE THREAD

**Issue by marekkaczkowski** [jeremyben/json-server-auth#13]
Hey,
I cannot start `json-server-auth` on MacOS due to incompatible line endings in `dist/bin.js`.
Following [this comment](https://github.com/OfficeDev/office-addin-validator/issues/20#issuecomment-352123135) (open `bin.js` and save with correct line endings) fixed problem.

**Comment by jeremyben** [comment]
Fixed in v2.0 with https://github.com/jeremyben/json-server-auth/commit/ed2483c53e6082f5beed6c758f9080218643ecbd
