### ISSUE TITLE
Problem running on Linux

### ISSUE THREAD

**Issue by leosuncin** [jeremyben/json-server-auth#16]
I'm unable to run `json-server-auth` from a NPM script

```json
"scripts": {
    "start": "run-p -r start:*",
    "start:cra": "react-scripts start",
    "start:json-server": "json-server-auth -p 3333 db.json",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
},
"proxy": "http://localhost:3333",
```

<pre>
$  npm run start:json-server

&gt; xstate-playground@0.1.0 start:json-server /home/user/projects/xstate-playground
&gt; json-server-auth -p 3333 db.json

/usr/bin/env: «node\r»: Not found file or directory
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! xstate-playground@0.1.0 start:json-server: `json-server-auth -p 3333 db.json`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the xstate-playground@0.1.0 start:json-server script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user/.npm/_logs/2020-02-12T20_04_55_632Z-debug.log
</pre>
</details>

The problem is relates to `End of Line (EOL)` character, in your case `CRLF` but in Linux and Mac the `EOL` is `LR`

# Reproduction repository

https://github.com/leosuncin/xstate-playground

**Comment by jeremyben** [comment]
fixed in v2.0 by https://github.com/jeremyben/json-server-auth/commit/ed2483c53e6082f5beed6c758f9080218643ecbd
