### ISSUE TITLE
"Email and password are required"

### ISSUE THREAD

**Issue by AAfify1** [jeremyben/json-server-auth#19]
I keep getting a 400 bad response with the message "Email and password are required".  I am using Postman with all the info in the screenshot below. Please help.
![Screen Shot 2020-04-07 at 12 27 48 PM](https://user-images.githubusercontent.com/15859023/78658986-328cbd80-78cb-11ea-966b-505158cb6797.png)

**Comment by ArtieFuzzz** [comment]
its in text turn it to json should be on the top bar
![image](https://user-images.githubusercontent.com/48877462/79206653-ff29d000-7e82-11ea-98af-938760c2ea77.png)
