### ISSUE TITLE
404 Not Found

### ISSUE THREAD

**Issue by ArtieFuzzz** [jeremyben/json-server-auth#20]
i'm running the JSON Server on glitch.com and i'm using postman to post the data and when i send the request nothing seemed to happen and i got the status 404 Not Found am i missing something or doing something wrong?
![image](https://user-images.githubusercontent.com/48877462/79178541-e6042d80-7e48-11ea-8564-5b9243ac7d6f.png)

**Comment by ArtieFuzzz** [comment]
i'm kinda new to this stuff

**Comment by ArtieFuzzz** [comment]
just a slight update
![image](https://user-images.githubusercontent.com/48877462/79206538-d275b880-7e82-11ea-80bd-ff7a06f84daf.png)

**Comment by ArtieFuzzz** [comment]
worked for me now .-.

**Comment by sergiober73** [comment]
I have the same problem. How do you fix it?

**Comment by danielcolrod** [comment]
What did you do to fix it?
