### ISSUE TITLE
Problems when creating resource with owner-only writing.

### ISSUE THREAD

**Issue by Daniel-Ayala** [jeremyben/json-server-auth#21]
Hello. I tried to set up a json-server-auth API. I want a resource to only be modifiable by the owner so I used code 644 in the route. However, when I try to *create* a new resource of the kind with a logged user, including the token in the header as "'Authorization': 'Bearer xxx.xxx.xxx'" I get a "Forbidden" error. There is no information in the documentation about the creation of resources or how the permissions affect it (since the new element to be introduced has, technically, no userId when it is sent).

**Comment by jeremyben** [comment]
You should definitely add a `userId` property if you want to create a private ressource. That's the point.

If you looked at the 403 error body, you would see that this case sends the following message:
`'Private resource creation: request body must have a reference to the owner id'`
