### ISSUE TITLE
 Is giving incorrect password but I put the same bank data

### ISSUE THREAD

**Issue by mabitten** [jeremyben/json-server-auth#22]
![erro-json-server-auth](https://user-images.githubusercontent.com/25987557/79889416-5c1e0c80-83d4-11ea-8181-b68f634620f2.png)

I'm having an incorrect password error even putting the same data in the json file

**Comment by ArtieFuzzz** [comment]
your password is encypted so you can't do that

**Comment by ArtieFuzzz** [comment]
your password after you register should look liek this 
![image](https://user-images.githubusercontent.com/48877462/83322360-4edd2300-a29a-11ea-84c8-a4d3ac3bf627.png)
