### ISSUE TITLE
integrate json-server-auth with express server 

### ISSUE THREAD

**Issue by kambleaa007** [jeremyben/json-server-auth#23]
const path = require("path");
const express = require("express");
const app = express();
const DIR = "";
const PORT = 3000;
var jsonServer = require("json-server");
const auth = require("json-server-auth");

app.use("/", jsonServer.router("db.json"));
app.use(auth);

app.listen(PORT, () => console.log("server started on " + PORT));

old code without express
const jsonServer = require("json-server");
const auth = require("json-server-auth");

const app = jsonServer.create();
const router = jsonServer.router("db.json");
const middlewares = jsonServer.defaults();
const port = process.env.PORT || 3000;

const cors = require("cors"); // need to install cors

// /!\ Bind the router db to the app
app.db = router.db;
app.use(auth);
app.options("*", cors());

app.use(middlewares);
app.use(router);

app.listen(port);

**Comment by jeremyben** [comment]
I don't understand your issue, please be more explicit. This is a bunch of code and I'm not a compiler.

What I think I get is : you want to bind json-server itself to an express router, then  you should look at the json-server documentation. Json-server already uses express as a direct dependency.
