### ISSUE TITLE
How to change user password from client ?

### ISSUE THREAD

**Issue by AlenKelemen** [jeremyben/json-server-auth#28]
Code for this is in TODO comment, am I right ?
from code:

/**
 * Patch and Put user
 */
// TODO: create new access token when password or email changes

**Comment by eggn** [comment]
PATCH or PUT /users/:id  does not encrypting the password. I think that is a bug. 
As workaround I have used the follow middleware in my json server:
//Middleware for encrypt the password
server.use((req, res, next) => { 
  if (req.url.indexOf('users') != -1 &&
      req.method === 'PATCH' || req.method === 'PUT' &&
      req.body.password) {
    bcrypt
      .hash(req.body.password, 10)
      .then((hash) => {
        req.body.password = hash
        next()
      })
      .catch(next)    
  }else{
    next() // Simply continue with json-server router
		return
  }
})

**Comment by jeremyben** [comment]
Fixed in 2.1.0 with https://github.com/jeremyben/json-server-auth/commit/4382ef1a41dfa90734719eb2cc163c355ec0d733
