### ISSUE TITLE
Error: Cannot find module 'json-server-auth/guards'

### ISSUE THREAD

**Issue by siamkreative** [jeremyben/json-server-auth#3]
Bonjour :)

I followed the documentation about the [Permissions Rewriter](https://github.com/jeremyben/json-server-auth#permisssions-rewriter) but there seems to be an issue when I am requiring the module:
```js
const { rewriter } = require('json-server-auth/guards');
```

Here is the whole code for your reference:
```js
const jsonServer = require('json-server');
const auth = require('json-server-auth');
const { rewriter } = require('json-server-auth/guards');

const app = jsonServer.create();
const router = jsonServer.router('db.json');
const port = process.env.PORT || 3000;

// Bind the router db to the app
app.db = router.db;

// Permission rules
const rules = rewriter({
    users: 600,
    clients: 600,
    reports: 600
});

app.use(auth);
app.use(rules);
app.use(router);
app.listen(port);
```

What am I doing wrong?

**Comment by jeremyben** [comment]
Oui, sorry about that, I forgot about the build step.
It's actually :
```js
const { rewriter } = require('json-server-auth/dist/guards');
```
I know it's not ideal, but it's temporary before I improve this part.
Merci de prévenir !

**Comment by siamkreative** [comment]
Thanks for the blazing fast reply, much appreciated!

I have now adjusted my code accordingly, and the module gets imported correctly. This, however, leads to a new error: **all my endpoints now return 404**.

If I comment out `app.use(rules);` (disabled the rewriter), all endpoints work fine but are obviously not protected.

**Comment by jeremyben** [comment]
Yes sorry again, this is not well documented and it's one of the many tricks to know when you use json-server-auth programmatically.

You must apply the rewrite rules middleware **before** the auth middleware, which itself must be applied before the router middleware.

So the only correct order would be :
```js
app.use(rules);
app.use(auth);
app.use(router);
```

**Comment by siamkreative** [comment]
Thanks again for helping with this! Merci bien

**Comment by jeremyben** [comment]
@SiamKreative I just updated the module and now you can simply access the rewriter from the module  like this:

```js
const auth = require('json-server-auth')
const rules = auth.rewriter(...)
```
Readme has been updated.
