### ISSUE TITLE
npm installation does not work, looking for non existent path

### ISSUE THREAD

**Issue by filiphric** [jeremyben/json-server-auth#32]
I’m having trouble with installation using `npm install -D json-server-auth` I have `json-server` already installed. I get an error: ENOENT: no such file or directory, chmod `/Users/{username}/{myapp}/node_modules/json-server-auth/dist\bin.js` seems to me that the reference to `dist\bin.js` might be the problem.

Using mac OS 10.15.3 
Node v12.13.1
NPM v6.12.1

I tried removing node_modules, deleting package.lock.json, and then trying to install again, but with no luck. getting the same error.

yarn installation worked with no problem

**Comment by theWickedWebDev** [comment]
Same issue here

**Comment by gulshanvasnani** [comment]
Same issue even for me.
It is working in version 1.2.1
But it is not working starting from version 2.0.0.

**Comment by jeremyben** [comment]
Starting with version 2.0.0, json-server is now a peer dependency and no longer a direct one. so you need to install json-server as well.

**Comment by ChakirMrabet** [comment]
Installation fails, even with json-server installed:

**ENOENT: no such file or directory, chmod '/home/......./node_modules/json-server-auth/dist\bin.js'**

In my package.json I have json-server:

 **"json-server": "^0.16.3",**

Using npm 6.4.1 .

It looks like json-server-auth is trying to find an older version of json-server?

**npm WARN json-server-auth@2.0.2 requires a peer of json-server@^0.15 but none is installed. You must install peer dependencies yourself.**

Thanks.

**Comment by jeremyben** [comment]
Fixed in 2.1.0 with https://github.com/jeremyben/json-server-auth/commit/89af19ef636136d8db389879857282cfc6a1636f
