### ISSUE TITLE
How Is This Different From jsonwebtoken?

### ISSUE THREAD

**Issue by opticyclic** [jeremyben/json-server-auth#37]
I got here by searching the json-server issues
https://github.com/typicode/json-server/issues/897

However, a much earlier issue mentions using jsonwebtoken
https://github.com/typicode/json-server/issues/190

Which links to:
https://www.techiediaries.com/fake-api-jwt-json-server/

How is this different?

Do you have a list of pros and cons of the different approaches?

**Comment by piotr-cz** [comment]
This package is implementing features described in article referenced by You and does lot of other related useful things 
It uses `jsonwebtoken` as a dependency to handle with json web tokens.
