### ISSUE TITLE
"Incorrect password"

### ISSUE THREAD

**Issue by farmeroscar** [jeremyben/json-server-auth#38]
Hi, 4 hours of trying to login. I would so much like to use json-server-auth. Can you help?

Below I am showing HTTPie, but trials with Postman, wget and cURL have also frustrated me.

**CLI:**

npm run start

**generates:**

> json-server-auth@1.0.0 start /Users/oscar/developer/carmen/jsonGUI/json-server-auth-folder
> json-server-auth db.json
  Loading db.json
  Loading /Users/oscar/developer/carmen/jsonGUI/json-server-auth-folder/node_modules/json-server-auth/dist
  Done
  Resources
  http://localhost:3000/users
  Home
  http://localhost:3000
GET /users 200 6.634 ms - 90

**CLI:** 
`http POST localhost:3000/login email=olivier@mail.com password=bestPassw0rd
`

**generates:**. 

HTTP/1.1 400 Bad Request
Access-Control-Allow-Credentials: true
Cache-Control: no-cache
Connection: keep-alive
Content-Length: 20
Content-Type: application/json; charset=utf-8
Date: Sun, 11 Oct 2020 17:18:18 GMT
ETag: W/"14-iEk1d6UpQuw3XSfG5Pju721C6OA"
Expires: -1
Keep-Alive: timeout=5
Pragma: no-cache
Vary: Origin, Accept-Encoding
X-Content-Type-Options: nosniff
X-Powered-By: Express

"Incorrect password"

**CLI:** 
`http localhost:3000/users `

**generates:**

[
    {
        "email": "olivier@mail.com",
        "id": "1",
        "password": "bestPassw0rd"
    }
]

Looking forward to hear from you.
Many thanks,
Oscar

**Comment by DjulLau** [comment]
Hi. I think this is because the password is wrongly stored in clear but should be hashed (bcryptjs).

**Comment by farmeroscar** [comment]
Spot on 👍 Many thanks! It would definitely have helped me if this had been made explicit in README.md

So, I went on-line to https://bcrypt-generator.com/ and entered bestPassw0rd and received back a hash string, which I entered into db.json.

Now my CLI command <http localhost:3000/users> generates:
[
    {
        "email": "olivier@mail.com",
        "id": "1",
        "password": "$2b$10$rgPZW15anuq83hiGT.I4Ge0PNPyXtBjFAXSd0s23bp2kzstvQHm4e"
    }
]

and  my CLI command <http POST :3000/login email="olivier@mail.com" password="bestPassw0rd"> generates a token:

{
    "accessToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im9saXZpZXJAbWFpbC5jb20iLCJpYXQiOjE2MDI1MjUzMzcsImV4cCI6MTYwMjUyODkzNywic3ViIjoiMSJ9.8hhNmfCmTUHNQGoefzGBb0xFF1Nj6_3uyUC_5qUeP-g"
}
