### ISSUE TITLE
Create a profile resource or returns the user id on login request

### ISSUE THREAD

**Issue by FelipeOliveiraDvP** [jeremyben/json-server-auth#40]
Please, you could return the user ID in the login request or create a profile route, where only the logged in user can view and change the data of his account. Thanks.

**Comment by AmadoGuerrero** [comment]
@FelipeOliveiraDvP  the user id is already returned in the accessToken itself. Once you decode the accessToken, the `sub` property holds the id.

**Comment by myflowpl** [comment]
@FelipeOliveiraDvP the profile resource is really good idea, you just use your token to get the full model, in 99% cases you will have to have this data to show it in your ui app.

@AmadoGuerrero yes, you are right, but first of all, you will have to install extra library to decode jwt & decode, this is extra unnecessary coding, it's not big deal but when you teach new people to do frontend, they have a lot of new stuff to learn, then simple i better

even better would be to return the user object with the token itself, so no more requests is required 

thanks for your work, love it 💪

**Comment by manniniandrea** [comment]
I've created a pull request #43 to return user's accessory data, as you can read in the pull request itself,  I thought it could be recklessly added without any additional parameters and without making it a breaking change.

**Comment by jeremyben** [comment]
`user` object added to `register` and `login` responses in 2.1.0 with https://github.com/jeremyben/json-server-auth/commit/5af16c940e8a41b0bd81c478813827561eb2d5b9

Thank you @manniniandrea for your PR :)
